apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app: zilliqa-exporter
  name: zilliqa-exporter.rules
spec:
  groups:
  - name: zilliqa-exporter.records
    rules:
    - record: zilliqa:network:epoch
      expr: max(epoch) by (cluster_name, network_name)
    - record: zilliqa:epoch:outofsync
      expr: zilliqa:network:epoch - on(cluster_name, network_name) group_right(pod_name, public_ip) epoch

  - name: zilliqa-exporter.alerts
    rules:
    - alert: OutOfSync
      annotations:
        message: 'Node {{ $labels.pod_name }} is {{ $value }} epochs behind the network'
      expr: 5 > zilliqa:epoch:outofsync >= 3
      for: 5m
      labels:
        severity: warning
    - alert: OutOfSync
      annotations:
        message: 'Node {{ $labels.pod_name }} is {{ $value }} epochs behind the network, node maybe stalled'
      expr: zilliqa:epoch:outofsync > 5
      for: 5m
      labels:
        severity: critical
    - alert: OutOfStorage
      annotations:
        message: 'Storage usage of {{ $labels.pod_name }} reached {{ printf "%.2f" $value }}%'
      expr: storage_used / storage_total * 100 > 75
      for: 5m
      labels:
        severity: warning
    - alert: ApiServerDown
      annotations:
        message: 'API server of {{ $labels.pod_name }} is not at service'
      expr: api_server_up == 0
      for: 5m
      labels:
        severity: critical
    - alert: StatusServerDown
      annotations:
        message: 'Status server of {{ $labels.pod_name }} is not at service'
      expr: admin_server_up == 0
      for: 5m
      labels:
        severity: critical
    - alert: NetworkStall
      annotations:
        message: 'Latest Tx block was mined {{ printf "%.2f" $value }} minutes ago, network maybe stalled'
      expr: (time() - (latest_txblock_timestamp / 1e3)) / 60 > 2
      for: 14m
      labels:
        severity: critical
    - alert: ZilliqaProcessNotRunning
      annotations:
        message: 'No running zilliqa process found in node {{ $labels.pod_name }}'
      expr: zilliqa_process_running == 0
      for: 5m
      labels:
        severity: critical
    - alert: ZilliqaProcessRestarted
      annotations:
        message: 'Zilliqa process of node {{ $labels.pod_name }} restarted recently'
      expr: delta(node_uptime[10m]) < 0
      for: 1m
      labels:
        severity: warning
    - alert: ConnectionBurst
      annotations:
        message: 'Node {{ $labels.pod_name }} TCP connection count burst of zilliqa process detected'
      expr: delta(connection_count[1m]) > 100
      for: 5m
      labels:
        severity: warning
    - alert: ThreadBurst
      annotations:
        message: 'Node {{ $labels.pod_name }} Thread count burst of zilliqa process detected'
      expr: delta(thread_count[1m]) > 100
      for: 5m
      labels:
        severity: warning
    - alert: FdBurst
      annotations:
        message: 'Node {{ $labels.pod_name }} File descriptor count burst of zilliqa process detected'
      expr: delta(fd_count[1m]) > 100
      for: 5m
      labels:
        severity: warning
    # TODO: add container_name
    - alert: ContainerCPUUsageHigh
      annotations:
        message: 'Node {{ $labels.pod_name }} container CPU usage percent of total limit is above {{ printf "%.2f" $value }}%'
      expr: rate(container_cpu_usage_seconds[1m])  * 100 /  container_cpu_cores_limit_equivalence > 75
      for: 5m
      labels:
        severity: warning
    - alert: ContainerMemoryUsageHigh
      annotations:
        message: 'Node {{ $labels.pod_name }} container memory usage percent of total limit is above {{ printf "%.2f" $value }}%'
      expr: container_mem_usage_bytes / container_mem_limit_bytes * 100 > 75
      for: 5m
      labels:
        severity: warning
    - alert: NodeNotInNetwork
      annotations:
        message: 'Node {{ $labels.pod_name }} is "{{ $labels.text }}"'
      expr: node_type == 0
      for: 5m
      labels:
        severity: warning
