{
 "title": "Zilliqa / Overview",
 "description": "Overview of Zilliqa Network",
 "tags": [ "zilliqa" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "network",
    "label": "Network",
    "query": "label_values(node_info, network_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "min(node_uptime{network_name=\"$network\",type!=\"\"})"
    }
   ]
  },
  {
   "title": "Health Status",
   "type": "stat",
   "description": "Max epoch left behind the network of all nodes\n0-3: healthy\n3-5: unhealthy",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(epoch{network_name=\"$network\"}) - min(epoch{network_name=\"$network\"})"
    }
   ]
  },
  {
   "title": "Latest Tx Block",
   "type": "stat",
   "description": "Time since latest Tx block mined",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(time() - max(latest_txblock_timestamp / 1e3) by (network_name, cluster_name))"
    }
   ]
  },
  {
   "title": "Node Status",
   "type": "table-old",
   "gridPos": { "h": 24, "w": 18, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "sum(epoch{network_name=\"$network\"}) by (pod_name, type, public_ip)"
    },
    {
     "expr": "sum(zilliqa:epoch:outofsync{network_name=\"$network\"}) by (pod_name)"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds{network_name=\"$network\"}[1m]) / container_cpu_cores_limit_equivalence{network_name=\"$network\"}) by (pod_name)"
    },
    {
     "expr": "sum(container_mem_usage_bytes{network_name=\"$network\"} / container_mem_limit_bytes{network_name=\"$network\"}) by (pod_name)"
    }
   ]
  },
  {
   "title": "Synced/Total Nodes",
   "type": "gauge",
   "description": "Synced means \"Tx blocks left behind network\" <= 3",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(zilliqa:epoch:outofsync{network_name=\"$network\",type!=\"\"} <= 3) / count(node_info{network_name=\"$network\",type!=\"\"})"
    }
   ]
  },
  {
   "title": "Block Height",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(num_tx_blocks{network_name=\"$network\"})"
    }
   ]
  },
  {
   "title": "DS Block Height",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(num_ds_blocks{network_name=\"$network\"})"
    }
   ]
  },
  {
   "title": "Sharding Nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(sharding_peers{network_name=\"$network\"})"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(node_info{network_name=\"$network\",type!=\"\"})"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(num_transactions{network_name=\"$network\"})"
    }
   ]
  },
  {
   "title": "Sharding Structure",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "max(sharding_peers{network_name=\"$network\"}) by (index)"
    }
   ]
  },
  {
   "title": "Node Structure",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 16 },
   "targets": [
    {
     "expr": "count(node_info{network_name=\"$network\", type!=\"\"}) by (type)"
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "table-old",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum(ALERTS{alertname!=\"Watchdog\"}) by (alertname, alertstate, pod, severity, job)"
    }
   ]
  }
 ]
}