{
 "title": "Zilliqa / Node",
 "description": "Zilliqa Node Status",
 "tags": [ "zilliqa" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "network",
    "label": "Network",
    "query": "label_values(node_info, network_name)"
   },
   {
    "name": "type",
    "label": "NodeType",
    "query": "label_values(node_info{network_name=\"$network\"}, type)"
   },
   {
    "name": "index",
    "label": "Index",
    "query": "label_values(node_info{network_name=\"$network\", type=\"$type\"}, pod_name)"
   }
  ]
 },
 "panels": [
  { "title": "Block Chain Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Sync Status",
   "type": "stat",
   "description": "How many epoch left behind the network\n0-3: healthy\n3-5: unhealthy",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "zilliqa:epoch:outofsync{network_name=\"$network\", type=\"$type\", pod_name=~\".*-$index\"}"
    }
   ]
  },
  {
   "title": "Epoch",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "epoch{network_name=\"$network\", type=\"$type\", pod_name=~\".*-$index\"}"
    }
   ]
  },
  {
   "title": "DS Epoch",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "ds_epoch{network_name=\"$network\", type=\"$type\", pod_name=~\".*-$index\"}"
    }
   ]
  },
  {
   "title": "API Server",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "api_server_up{network_name=\"$network\", type=\"$type\", pod_name=~\".*-$index\"}"
    }
   ]
  },
  {
   "title": "Node Type",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_type{network_name=\"$network\", type=\"$type\", pod_name=~\".*-$index\"}"
    }
   ]
  },
  {
   "title": "Up Time",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "node_uptime{network_name=\"$network\", type=\"$type\", pod_name=~\".*-$index\"}"
    }
   ]
  },
  {
   "title": "Zilliqa Version",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_info{network_name=\"$network\", type=\"$type\", pod_name=~\".*-$index\"}"
    }
   ]
  },
  {
   "title": "Public IP",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_info{network_name=\"$network\", type=\"$type\", pod_name=~\".*-$index\"}"
    }
   ]
  },
  {
   "title": "Admin Server",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "admin_server_up{network_name=\"$network\", type=\"$type\", pod_name=~\".*-$index\"}"
    }
   ]
  },
  {
   "title": "Shard ID",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "shard_id{network_name=\"$network\", type=\"$type\", pod_name=~\".*-$index\"}"
    }
   ]
  },
  {
   "title": "Avaliability Zone",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 16, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_info{network_name=\"$network\", type=\"$type\", pod_name=~\".*-$index\"}"
    }
   ]
  },
  {
   "title": "Local IP",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_info{network_name=\"$network\", type=\"$type\", pod_name=~\".*-$index\"}"
    }
   ]
  },
  { "title": "Process Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Storage Used",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "storage_used{network_name=\"$network\", type=\"$type\", pod_name=~\".*-$index\"} / storage_total{network_name=\"$network\", type=\"$type\", pod_name=~\".*-$index\"}",
     "legendFormat": "used: {{cwd}}"
    }
   ]
  },
  {
   "title": "Storage Status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 4, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "storage_used{network_name=\"$network\", type=\"$type\", pod_name=~\".*-$index\"}",
     "legendFormat": "Used: {{cwd}}"
    },
    {
     "expr": "storage_total{network_name=\"$network\", type=\"$type\", pod_name=~\".*-$index\"}",
     "legendFormat": "Total: {{cwd}}"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "thread_count{network_name=\"$network\", type=\"$type\", pod_name=~\".*-$index\"}",
     "legendFormat": "PID: {{pid}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum((rate(container_cpu_usage_seconds_total{container=\"\", container_name!=\"\", pod_name=\"$network-$type-$index\"}[1m])))",
     "legendFormat": "$network-$type-$index"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(container_memory_usage_bytes{container=\"\", pod_name=\"$network-$type-$index\"})",
     "legendFormat": "Usage"
    },
    {
     "expr": "avg(container_spec_memory_limit_bytes{container=\"\", pod_name=\"$network-$type-$index\"})",
     "legendFormat": "Limit"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(connection_count{network_name=\"$network\", type=\"$type\", pod_name=~\".*-$index\"}) by (local_port, status)",
     "legendFormat": "{{local_port}} {{status}}"
    }
   ]
  },
  {
   "title": "File Discriptors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "fd_count{network_name=\"$network\", type=\"$type\", pod_name=~\".*-$index\"}",
     "legendFormat": "PID: {{pid}}"
    }
   ]
  }
 ]
}